### ISSUE TITLE
Files ignored by gitignore are not shaded 

### ISSUE THREAD

**Issue by Blakeinstein** [TheOld/vscode-fluent-ui#1]
Here is an example of what I mean.
![image](https://user-images.githubusercontent.com/42214598/129408403-f07ed15b-e585-41ca-9fac-3506d138c510.png)

As you can see

```
.cache
.parcel-cache
```

are not greyed out.

Huge thanks for this project btw! Loving the refreshed new look!

**Comment by TheOld** [comment]
Hey @Blakeinstein, good catch! I didn't even notice that while making this. I'll have a fix for that soon. Thanks!

**Comment by stoneC0der** [comment]
Are you sure it's not a vsCode bug, I just discover your extension and am about to try it on macOS 11, and adding a file to the .gitignore file does not work either. I came here first to look a the issues.

**Comment by Blakeinstein** [comment]
> Are you sure it's not a vsCode bug

## With Fluent UI
![image](https://user-images.githubusercontent.com/42214598/129663560-abcfe175-4b66-49e4-bf87-038eb0d05cd1.png)

## Without Fluent UI
![image](https://user-images.githubusercontent.com/42214598/129663606-303a2bc1-94a8-47be-879c-26c2ea84ee13.png)

**Comment by TheOld** [comment]
Thanks lads. I had a look and it seems that VSCode uses some special decorations for this and is not the most straight forward thing to override. I'm hoping to have a fix for it sometime today.

BTW, @Blakeinstein, there has been an update two days ago, you should have it already since they're automatic, but you need to run `> Fluent UI: Enable` again to see the changes.

**Comment by TheOld** [comment]
>as someone pointed in an other issues, Backdrop filter effects are expensive, actually don't work on macOS, also I can confirm that theme with a background other black/dark don't keep they editor.background color setting.

@stoneC0der, there's an option under Settings to allow users to toggle the backdrop filters on and off. You can disable it there.

Re: the other issues, can you open a new issue with some screenshots of the problems you're having? I'd be happy to work on possible fixes for macOS.

**Comment by TheOld** [comment]
@Blakeinstein I'm having a hard time finding a fix for that. It does not grey out ignored files on my VSCode, regardless of theme and if Fluent UI is enable or not. I suspect is some setting on my end that I can't find.
In any case, I've remove some of the overrides related to decorations on the sidebar, so most colors, if not all (like Git modified, etc) should be correct now.

**Comment by Blakeinstein** [comment]
@TheOld I will try to pin point the issue and if possible also try to send in a fix.

**Comment by Blakeinstein** [comment]
I am able to see a faint distinction now..

![image](https://user-images.githubusercontent.com/42214598/129837651-1ec3ba5a-d094-45d5-8cb8-9b9de110c41d.png)

**Comment by TheOld** [comment]
Hey, thanks @Blakeinstein. 
That's good. I guess I was overriding decorations unintentionally. Let me know if you're happy with the results and I'll close the issue.

**Comment by Blakeinstein** [comment]
That I am! I will close the issue myself.
