### ISSUE TITLE
Can't enable on ArchLinux

### ISSUE THREAD

**Issue by Hadi7546** [TheOld/vscode-fluent-ui#11]
After run Fluent-Ui: Enable i get:
![image](https://user-images.githubusercontent.com/77378037/137016599-bc3fa7a5-9b23-4542-85b0-6b6726327bb9.png)

**Comment by OmidHaqi** [comment]
download and replace [this](https://drive.google.com/file/d/1yzU4pruNyImpsAvie5SQPFt3N2HKVizq/view?usp=drive_link) 4 file in `/usr/share/code/resources/app/out/vs/code/electron-sandbox`

**Comment by SarfDime** [comment]
> download and replace [this](https://drive.google.com/file/d/1yzU4pruNyImpsAvie5SQPFt3N2HKVizq/view?usp=drive_link) 4 file in `/usr/share/code/resources/app/out/vs/code/electron-sandbox`
it still doesn't work, getting error command not found

**Comment by OmidHaqi** [comment]
> > download and replace [this](https://drive.google.com/file/d/1yzU4pruNyImpsAvie5SQPFt3N2HKVizq/view?usp=drive_link) 4 file in `/usr/share/code/resources/app/out/vs/code/electron-sandbox`
> it still doesn't work, getting error command not found
> 

What Linux distribution are you using and what method did you use to install vscode?

**Comment by SarfDime** [comment]
> > > download and replace [this](https://drive.google.com/file/d/1yzU4pruNyImpsAvie5SQPFt3N2HKVizq/view?usp=drive_link) 4 file in `/usr/share/code/resources/app/out/vs/code/electron-sandbox`
> > > it still doesn't work, getting error command not found
> 
> What Linux distribution are you using and what method did you use to install vscode?

Zorin and installed the deb package from the vs code site

**Comment by OmidHaqi** [comment]
copy files in `/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench`

**Comment by SarfDime** [comment]
> copy files in `/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench`

i did that yes, and i replaced the existing ones with the new ones, could the issue be that im not running vs code as sudo

**Comment by OmidHaqi** [comment]
I also use Zorin and installed the deb package, download and extract the zip file, and in the path you extracted the zip file, open the terminal and run this command.

`sudo cp -rf fui.js workbench.fui workbench.html workbench.js  /usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench
`

**Comment by OmidHaqi** [comment]
> > copy files in `/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench`
> 
> i did that yes, and i replaced the existing ones with the new ones, could the issue be that im not running vs code as sudo

I also use Zorin and installed the deb package, download and extract the zip file, and in the path you extracted the zip file, open the terminal and run this command.

`sudo cp -rf fui.js workbench.fui workbench.html workbench.js  /usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench `

**Comment by SarfDime** [comment]
> > > copy files in `/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench`
> > 
> > 
> > i did that yes, and i replaced the existing ones with the new ones, could the issue be that im not running vs code as sudo
> 
> I also use Zorin and installed the deb package, download and extract the zip file, and in the path you extracted the zip file, open the terminal and run this command.
> 
> `sudo cp -rf fui.js workbench.fui workbench.html workbench.js /usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench `

thanks it works now

**Comment by OmidHaqi** [comment]
Well done, every time you update vscode, copy the files again
