### ISSUE TITLE
No reminder to open VSC as Admin when disabling

### ISSUE THREAD

**Issue by PrabhieG** [TheOld/vscode-fluent-ui#13]
**Expected behaviour:** _Fluent UI for VS Code_ should remind users to launch VS Code as administrator when disabling the Fluent UI. It does remind the user to launch as Administrator when Enabling however so this may be a bug.
**Actual behaviour:** _Fluent UI for VS Code_ does nothing. Changes are not reverted. There is no pop up reminding the user to launch as administrator. This may result in the user being misled to believe that their VS Code installation is completely broken. The latest review on the [marketplace page](https://marketplace.visualstudio.com/items?itemName=leandro-rodrigues.fluent-ui-vscode&ssr=false#:~:text=UI%20is%20really%20nice%20but%20I%20cannot%20uninstall%20it%20completely%20it%20messed%20up%20all%20my%20vscode.%20Now%20I%20have%20to%20reinstall%20the%20vscode.) reflects this.

Furthermore please add to the README that Admin is required, although this may just be because I have a system wide installation rather than a user install.

**Comment by TheOld** [comment]
Hi @Tread-2036 , thanks for pointing that out. I've released a new version with updated instructions and reworked how the whole thing works, so it should be more reliable now.
