### ISSUE TITLE
Missing Scrollbars on Jupyter Notebooks

### ISSUE THREAD

**Issue by Arihant25** [TheOld/vscode-fluent-ui#14]
# Steps to Reproduce:
- Open a Jupter Notebook file in VS Code.
- There's no scrollbar on the side.
# Screenshot
![image](https://user-images.githubusercontent.com/22986534/140601567-7e2b6126-c9e1-4294-b465-753508bf89cf.png)

**Comment by TheOld** [comment]
Hey @Arihant25, I've pushed a new release with a fix for that issue. Please have a look and see of that works for you. Cheers.

**Comment by Arihant25** [comment]
Yes, it works!
