### ISSUE TITLE
It does not reload nor I can find fluent.js after several installing and uninstalling in Admin mode

### ISSUE THREAD

**Issue by syed-hamza-alee** [TheOld/vscode-fluent-ui#17]
![image](https://user-images.githubusercontent.com/34379602/148468350-b72f5e5d-1e05-4772-8546-214501a620bf.png)
I also face this error while runnin >Fluent: Reload. Developer mode reload just does not work

**Comment by TheOld** [comment]
It looks like you might be stuck with an old version. Which is strange considering that VSCode should auto update them whenever a new version is published.

Can you try following the instructions [here](https://github.com/TheOld/vscode-fluent-ui/issues/8#issuecomment-1016947924), see if that works for you?
