### ISSUE TITLE
Code installation appears to be corrupt after enabling fluent ui

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [TheOld/vscode-fluent-ui#18]
![屏幕截图 2022-01-22 101347](https://user-images.githubusercontent.com/62426149/150621071-94d1c6df-bd96-41c5-b8db-babffd134c9f.jpg)

**Comment by sam-the-programmer** [comment]
@CodeCrazy-ywt  why was this closed? I get that it happens, but is there a way we can prevent this/ I prefer this UI to the other one.

**Comment by CodeCrazy-ywt** [comment]
Because I thought I shouldn't have created this issue, instead I should have read README.MD
