### ISSUE TITLE
some suggestion

### ISSUE THREAD

**Issue by heartacker** [TheOld/vscode-fluent-ui#2]
thanks for you work,
and there is some suggestion for this UI
1. small sidebar dock width (strongly for me)
this wastes the space of Horizontal direction
![image](https://user-images.githubusercontent.com/1876302/129451546-72bd4fcf-3ec3-4d48-95cd-e9a5916ecbe8.png)

2. hover setting item
![image](https://user-images.githubusercontent.com/1876302/129451574-7e5a771a-4d0c-4c45-8d18-71c65929883a.png)

3.  the border of input box
![image](https://user-images.githubusercontent.com/1876302/129451603-f1181150-216a-40c3-9178-5393b1ef0c9f.png)

4. Un useful space of panel
![image](https://user-images.githubusercontent.com/1876302/129451629-3840571f-2f9a-48a2-abd1-dcace01d24bc.png)

5. rectangles rounded corners of editor bottom;
![image](https://user-images.githubusercontent.com/1876302/129451650-8f95c289-b4fd-4a11-9169-ad31ca045abd.png)

6. Bread crumbs 
![image](https://user-images.githubusercontent.com/1876302/129451729-a28894ea-b653-4b5b-8e0b-db29929bc2fc.png)

**Comment by TheOld** [comment]
Hi @heartacker, thanks for the feedback, much appreciated.

I'll go item to item to be clear:

1. The activity bar width is exactly the same as the vanilla (48px). What I did there was reduce the icon size and add a highlight to the active item (light grey colour). It might seem larger, but it's a perceived effect.
2. Dully noted. Will fix this soon.
3. Can you elaborate on that? What's wrong with the border there? You don't like it or is it too large?

4, 5 and 6 are being fixed along with some other layout issues.

Thanks!

**Comment by Blakeinstein** [comment]
I guess their point with the first one was that if the icons are smaller, then the activity bar being that size is just a waste of space, and can be reduced. Which does make sense.

**Comment by TheOld** [comment]
@heartacker The theme now has a compact mode, which will condense the spacing on some of the container elements, most notably the Activitybar. You can find the option under settings.
You'll also not that there were other layout fixes based on your observations. 

Thanks for that!
