### ISSUE TITLE
Please give Regular updates to this extension and fix some issues on monokai pro theme

### ISSUE THREAD

**Issue by fisforfaheem** [TheOld/vscode-fluent-ui#21]
I love your extension, and love the work you have done and put your effort on this project, I wish more people knew about this.

Also I wish this extension becomes more amazing with new UI and features, Please never give up on this feature! as you are a masterpieces

**Comment by TheOld** [comment]
Hey, updates are back. Had to be away from it for a while. There's been a few updates already, so go have a look at them if you haven't yet.
