### ISSUE TITLE
Sidebar not rounded unless theme is changed

### ISSUE THREAD

**Issue by SubjunctiveQuaver** [TheOld/vscode-fluent-ui#23]
When loading up VS code with the theme, the sidebar appears with sharp corners:

![image](https://user-images.githubusercontent.com/49895442/164143846-79a95c4f-930d-4503-81a1-45c4e751c150.png)

Reloading the window or running "Fluent UI: reload" doesn't work. Upon changing colour theme and back, it fixes the issue:

![image](https://user-images.githubusercontent.com/49895442/164144061-e0e16764-4041-4f2a-85aa-278b8fcd0e12.png)

**Comment by SubjunctiveQuaver** [comment]
Hiding and reopening the sidebar doesn't fix it either, it seems like only a theme change (and back) helps...

**Comment by ayushgun** [comment]
The explorer colors are also switched back to the theme colors.

**Comment by TheOld** [comment]
Hi, thanks for that. 
The latest release contains a fix for this issue.
Please, have another go and let me know how that works for you.

Cheers.
