### ISSUE TITLE
Transparency too high in some menus

### ISSUE THREAD

**Issue by SubjunctiveQuaver** [TheOld/vscode-fluent-ui#24]
See picture:

![image](https://user-images.githubusercontent.com/49895442/164144723-935ec462-5f06-457a-9333-949226dafe62.png)

This is inconsistent with menus such as this one which have more reasonable transparency:

![image](https://user-images.githubusercontent.com/49895442/164144838-34e54885-f4c7-453f-b682-e4be90a2e8b2.png)

**Comment by SubjunctiveQuaver** [comment]
This issue only occurs when reloading the theme, it seems:

![image](https://user-images.githubusercontent.com/49895442/164144952-48f8ac76-c58b-4681-8a36-5a2653335242.png)

This is before changing the theme (to try and fix the square sidebar issue)

**Comment by TheOld** [comment]
Hi,
This was fixed on the latest version.
Thanks.
