### ISSUE TITLE
Cannot disable theme (persists on uninstall, even after "disabling")

### ISSUE THREAD

**Issue by SubjunctiveQuaver** [TheOld/vscode-fluent-ui#25]
As per title. I had to reinstall VS Code for the theme to disappear...

**Comment by notAperson535** [comment]
@SubjunctiveQuaver you have to run vscode as "admin" to disable it

**Comment by notAperson535** [comment]
@SubjunctiveQuaver it says it the upgrade process
![image](https://user-images.githubusercontent.com/95918679/172206786-8264e594-e7c3-472d-aa20-693399482ba0.png)
