### ISSUE TITLE
Enabling Fluent UI makes it impossible to change the caret (cursor) color.

### ISSUE THREAD

**Issue by ELowry** [TheOld/vscode-fluent-ui#26]
Fluent UI overrides the cursor (caret) color to a somewhat dark blue. This makes it extremely difficult to see when using a dark background and a theme with blue text in many places (such as the default dark VS Code theme).

The settings override that can normally set the caret color ([https://stackoverflow.com/a/50201205](https://stackoverflow.com/a/50201205)) does not work when Fluent UI is enabled.

I am unsure of what is possible to solve this; but a here are some approaches that might be good if possible:

- Read the settings I linked to above and use those to color the caret if they are defined.
- Include an option in the settings to override the caret color.
- Make the caret white by default in dark mode in order to ensure a minimum amount of contrast.

**Comment by TheOld** [comment]
Hey @ELowry, sorry about the (very long) delay on this.
I'm addressing that and it'll be fixed on a coming release; The caret will no longer have the color hard-coded. So you'll be able to set the color to whatever you want. 
Thanks!
