### ISSUE TITLE
Sharp bottom corners of editor

### ISSUE THREAD

**Issue by SilverMarcs** [TheOld/vscode-fluent-ui#27]
![image](https://user-images.githubusercontent.com/77480421/177851510-8e2a17f7-5c2e-4193-87d8-1095b29d5a32.png)

The editor area has sharp corners on both right and left corners. Switching back and forth between themes does not make it rounded.

**Comment by TheOld** [comment]
You have no idea how much that bothers me, but I couldn't find a way of fixing that so far 😢 
It is definitely on my list of fixes though, so I'll close this one for the time being.

Thanks.
