### ISSUE TITLE
Doesn't work with version 1.70

### ISSUE THREAD

**Issue by theworldstanduser** [TheOld/vscode-fluent-ui#29]
Doesn't work with version 1.70

**Comment by notAperson535** [comment]
@apikeev here is a fixed compiled `.vsix` file that you can install as an extension
[fluent-ui-vscode-2.0.4.vsix.zip](https://github.com/TheOld/vscode-fluent-ui/files/9385519/fluent-ui-vscode-2.0.4.vsix.zip)
:

**Comment by TheOld** [comment]
Version `2.1.0` is out now with a fix for this issue.
