### ISSUE TITLE
Error When Enabling (Ran App as Administrator)

### ISSUE THREAD

**Issue by TwigCoder** [TheOld/vscode-fluent-ui#32]
![image](https://user-images.githubusercontent.com/62672426/187080399-0d100896-0fb0-40d9-94dd-1e3781ec296e.png)

I ran VS Code as an administrator and attempted to enable the Fluent UI. I have installed and reinstalled both VS Code and VS Code Insiders.

**Comment by dzgeorgy** [comment]
If VSCode version is 1.70 it won't work #29

**Comment by TheOld** [comment]
Hi, version `2.1.0` is out now with a fix for this issue.
