### ISSUE TITLE
Doesn't work with 1.71.0

### ISSUE THREAD

**Issue by kuroehanako** [TheOld/vscode-fluent-ui#33]
![화면 캡처 2022-09-07 124043](https://user-images.githubusercontent.com/78864678/188783779-77f8a45e-4133-4e59-af4c-3206b7e09751.png)

I installed fixed version. [Here](https://github.com/TheOld/vscode-fluent-ui/issues/29)

**Comment by TheOld** [comment]
Version `2.1.0` is out now with a fix for this issue.
