### ISSUE TITLE
Error while trying to enable the extension (v2.1) on vs-code (v1.72)

### ISSUE THREAD

**Issue by dim26** [TheOld/vscode-fluent-ui#34]
![image](https://user-images.githubusercontent.com/75603937/194815426-924461b1-d865-4f5e-80f0-41bccbdb3d53.png)

**Comment by 1Yanik3** [comment]
same error for me too (tried on win10, mac, and win 11) using both normal vs-code and insiders

**Comment by esibruti** [comment]
Version 3.0.0 and I have this problem. 
![image](https://user-images.githubusercontent.com/78214358/194936620-aa9662c4-c5f8-491f-b093-1be55024ee9a.png)
How do I resolve this issue?

**Comment by esibruti** [comment]
> Hey folks, the latest `3.0.1` version is out fixing this issue. Let me know if that works. There will be more fixes coming out soon.
> 
> Thanks.

Hello. I just installed this new version and it is working correctly. Thanks for the quick fix.
I didn't know about this extension but it looks amazing. I can't wait for the next changes.

**Comment by TheOld** [comment]
Glad to know it works for you!
