### ISSUE TITLE
How did you get the custom css elements

### ISSUE THREAD

**Issue by notAperson535** [TheOld/vscode-fluent-ui#37]
Hello, I was thinking about making a custom css for vscode, but was wondering where you got the elements from.

**Comment by TheOld** [comment]
What do you mean? VSCode DOM elements? If so, you can run the `> Developer: Toggle Developer Tools` command and that will open up a devtools panel, just like you do in Chrome or other browsers. From there is just a matter of inspecting the DOM and targeting what you want.

**Comment by notAperson535** [comment]
@TheOld That is what I wanted. Thank you!
