### ISSUE TITLE
Error while trying to enable the extension (v3.6.0) on vs-code (v1.72.1)

### ISSUE THREAD

**Issue by QWERT-commits** [TheOld/vscode-fluent-ui#39]
![image](https://user-images.githubusercontent.com/64510408/195593219-58877c8f-88eb-4289-9fd5-73501dda6da3.png)
Issue: The extension shows an error. It also notifies that I need to run VS code in admin mode to enable it (I am already in admin mode).
Some specific information provided in the image below:
![image](https://user-images.githubusercontent.com/64510408/195595915-8c378ca2-c58e-42e1-9e1e-e982602dedb5.png)

**Comment by TheOld** [comment]
Hey @QWERT-commits, would you mind opening up the developer tools (from the command palette `> Developer: Toggle developer tools`) and grabbing a screenshot of the console when you try to enable the extension, please?
I haven't seen that one before and currently I'm unable to reproduce it.

**Comment by QWERT-commits** [comment]
Here is the console when I tried to enable the extension, the part marked with the red line will reappear when I tries to enable the extension again.
![image](https://user-images.githubusercontent.com/64510408/196594363-f9866b1a-aac6-4bbd-975b-a86a9c8b9b06.png)

**Comment by TheOld** [comment]
I think I found what's causing the issue. Seems to be related to the part of the code that samples your wallpaper to create the blurred background. 
Do you have a regular image (jpg, png, etc) as your wallpaper or a solid colour?

In the meantime, you could try installing using the `> Fluent UI: no background` command. That will bypass the wallpaper sampling phase. Should at least allow you to use the theme without that feature.

I shall have a fix for that soon.

**Comment by TheOld** [comment]
@QWERT-commits, I've released a new version `3.8` with a lot of fixes and some new features.
Have a go on that one and let me know how that works out for you, please.

**Comment by QWERT-commits** [comment]
Thank you, although the problem still appears in version 3.8, it is solved after I install it using the "> Fluent UI: no background" command. It seems that there may be two application installed on my computer conflicting: Rainmeter and BGinfo from the Systeminternals suite (Both can display text on the desktop and change its background).
