### ISSUE TITLE
Could you also publish to Open-VSX for people that use VSCodium

### ISSUE THREAD

**Issue by ErickHoward** [TheOld/vscode-fluent-ui#4]
That would be really helpful to people that use VSCodium. You can find documentation on how to do that at: https://open-vsx.org/

Thanks in advance.

**Comment by TheOld** [comment]
Certainly. I'll have a go later today!

**Comment by TheOld** [comment]
Here you go: https://open-vsx.org/extension/leandro-rodrigues/fluent-ui-vscode

**Comment by ErickHoward** [comment]
>Here you go: https://open-vsx.org/extension/leandro-rodrigues/fluent-ui-vscode

Wow that was quick! Thanks
