### ISSUE TITLE
[Feature request] Settings file?

### ISSUE THREAD

**Issue by ReadieFur** [TheOld/vscode-fluent-ui#42]
Hi there, I like your UI modifications here however I would prefer to make the UI darker and from quickly digging through your code you seem to have the default colour values hard-coded. Would it be possible to add a file that the user can configure to change the colour of the UI? While you mentioned the plugin is able to use themes, in my testing, changing the theme does not effect the background colours of the editor.  
Below are the two files I had spotted that hard-code the values:  
https://github.com/TheOld/vscode-fluent-ui/blob/9f5a6cbe7fa1f65dee7cfb6003cb4f1954037ef0/src/js/theme_template.js#L163  
https://github.com/TheOld/vscode-fluent-ui/blob/9f5a6cbe7fa1f65dee7cfb6003cb4f1954037ef0/src/css/dark_vars.css#L7  
I would've modified this myself (which I did do in the inspector) however when I tried to build the code into a package to test, VSC would give me a command not found error, hence why I am not making a PR (also becuase today is the first time I've looked into VSC plugins)

**Comment by ReadieFur** [comment]
In regards to when I mentioned I was unable to install the newly packaged plugin, I am getting the same issue as referenced [here](https://github.com/TheOld/vscode-fluent-ui/issues/8#issuecomment-1016947924) and where you give instructions to resolve the issue, the path for me dosen't seem to exist

**Comment by TheOld** [comment]
Hi @ReadieFur,

Interesting, I have some changes planned and making it a bit less rigid on the background colors aspect in one of them, so this is quite pertinent. 

Thanks, I'm adding that to the (near) future features.

**Comment by TheOld** [comment]
Hey @ReadieFur, check out the new version `3.8`. I've added a few options to the settings page. It will allow you to set custom values for the accent, dark and light background colors.

**Comment by ReadieFur** [comment]
Thanks 👍

**Comment by fisforfaheem** [comment]
i am gettign this first tiem user : command 'fluent-ui-vscode.enableEffects' not found
