### ISSUE TITLE
Can't enable, fluent.enableEffects not found

### ISSUE THREAD

**Issue by TylerMS887** [TheOld/vscode-fluent-ui#45]
I cannot enable the UI design. I'm using One Dark Pro, but enabling the default VS Code theme
does not work. I got this message on each attempt to enable the Fluent design:

![image](https://user-images.githubusercontent.com/115214762/204017759-9f69744d-e23b-49b7-9686-aba6a77f0d51.png)

Release info:
```
Version: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22622
```

**Comment by rojnwa** [comment]
Duplicate #43
