### ISSUE TITLE
How did you get those folder and file icons combined?

### ISSUE THREAD

**Issue by Xosten** [TheOld/vscode-fluent-ui#48]
Hey man, I came across your Fluent UI theme for VS Code and I love it!

I was wondering how you got those folder icons combined with files icons, like in the screenshot bellow.
![image](https://user-images.githubusercontent.com/11696836/214018791-752e16d3-ea39-4427-b250-327909b0f231.png)

Thanks in advance,
Cheers,

**Comment by TheOld** [comment]
Hey @Xosten, really sorry about the delay here.

It's been a while, but I believe the sidebar icons (or product icons) was [Fluent Icons](https://marketplace.visualstudio.com/items?itemName=miguelsolorio.fluent-icons). The Explorer ones I don't recall at all (and I change those more frequently than I should), I think it was either [Seti Icons](https://marketplace.visualstudio.com/items?itemName=qinjia.seti-icons) or [VSCode Great Icons](https://marketplace.visualstudio.com/items?itemName=emmanuelbeziat.vscode-great-icons).

**Comment by Xosten** [comment]
Hey @TheOld, thanks for having taken the time to reply with the icon names. Take care 😉 !
