### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by DimitrisMilonopoulos** [TheOld/vscode-fluent-ui#49]
@TheOld thank you for your amazing contributions on this extension.

Although the extension features have become very complete, there is still an issue where mac/linux users can not use the extension after 3.3.0, have tried to fix it myself but with no luck.

Is it something on your roadmap to add support for?

**Comment by Lamparter** [comment]
Yes, this project does seem to be dead 😢
However, I recently remade the styles and uploaded them on to GitHub.
I will create an issue with the link and how to use them in a second.
