### ISSUE TITLE
Does not work for WSL

### ISSUE THREAD

**Issue by shafayetejaman** [TheOld/vscode-fluent-ui#55]
It is not working in WSL. I always get the error: "Command 'Fluent UI: Enable' resulted in an error command 'fluent-ui-vscode-enableEffects' not found.

**Comment by g8row** [comment]
just enable it in a windows folder, it will work when in wsl

**Comment by shafayetejaman** [comment]
![image](https://github.com/TheOld/vscode-fluent-ui/assets/112795252/cbe66644-f9f3-4227-afc2-a7688be03005)
I tried both installing in wsl2 and uninstalling from there

**Comment by g8row** [comment]
open a windows folder in vscode, not a wsl one. install fluentui. disable transparency effects in the extension settings. run the enable command. it will complete and when you open a wsl folder the changes will be saved.
