### ISSUE TITLE
Issues with Padding missing font?

### ISSUE THREAD

**Issue by DimitrisMilonopoulos** [TheOld/vscode-fluent-ui#9]
This is how the find and replace looks:
![image](https://user-images.githubusercontent.com/14860553/133421918-d15775cf-6f43-43db-b322-2fd6e4833a16.png)

Buttons are missing here too, something to do with the padding I believe:

![image](https://user-images.githubusercontent.com/14860553/133421959-7e32aabe-5fcf-4cb4-a229-c15f6a0a81bf.png)

Do I have something wrong?

**Comment by TheOld** [comment]
Thanks @DimitrisMilonopoulos. I haven't seen that one before. It does indeed seem related to padding. 
I'll have a look soon.
BTW, are you using `Compact mode`?

Thanks!

**Comment by DimitrisMilonopoulos** [comment]
Can reproduce this with compact and without compact :)

**Comment by TheOld** [comment]
Hi @DimitrisMilonopoulos, I've looked into that and unfortunately I couldn't find a fix just yet. The thing I noticed is that if you toggle the `replace` mode by clicking the green button on the left it fixes itself.
